
CREATE TABLE Users (id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL , 
enabled BIT(1) NOT NULL, 
login VARCHAR(45) NOT NULL, 
password VARCHAR(80) NOT NULL, 
PRIMARY KEY (id));

CREATE TABLE Roles (id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL , 
rolename VARCHAR(45) NOT NULL, 
PRIMARY KEY (id));
