 drop table Roles if exists;
 drop table Users if exists;
 drop table user_roles if exists;


create table Roles (
        id bigint generated by default as identity (start with 1 ),
        rolename varchar(45) not null,
        primary key (id)
);

create table Users (
        id bigint generated by default as identity (start with 1),
        enabled boolean not null,
        login varchar(45) not null,
        password varchar(80) not null,
        primary key (id)
);

create table user_roles (
        user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
);

